import { useEffect, useState } from "react";
import { BarChart3, BriefcaseBusiness, Clock3, ShieldCheck, Users, Search, ChevronRight } from "lucide-react";
import api from "../services/api";
import Loading from "../components/Loading";
import ErrorMessage from "../components/ErrorMessage";
import AppLayout from "../components/AppLayout";

export default function AdminDashboard(){
  const [data,setData]=useState(null); const [error,setError]=useState(""); const [search,setSearch]=useState("");
  useEffect(()=>{api.get("/admin/dashboard").then(r=>setData(r.data)).catch(e=>setError(e.response?.data?.message||"Could not load admin dashboard"));},[]);
  if(!data&&!error)return <Loading text="Loading admin dashboard..."/>;
  const candidates=(data?.candidates||[]).filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(search.toLowerCase()));
  return <AppLayout admin><main className="mx-auto max-w-[1450px] px-5 py-7 sm:px-8">
    {error&&<ErrorMessage message={error}/>}<div><p className="text-sm font-medium text-violet-600">Admin workspace</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Candidates</h1><p className="mt-2 text-slate-500">Manage candidates, interviews and platform performance.</p></div>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminStat icon={Users} label="Total Candidates" value={data?.totalCandidates}/><AdminStat icon={BriefcaseBusiness} label="Total Interviews" value={data?.totalInterviews}/><AdminStat icon={BarChart3} label="Average Score" value={`${Math.round(data?.averageScore||0)}%`}/><AdminStat icon={Clock3} label="Active Candidates" value={data?.activeCandidates}/></section>
    <section className="mt-7 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5"><div><h2 className="text-lg font-bold text-slate-900">Candidates</h2><p className="mt-1 text-sm text-slate-500">Candidate activity and average interview score.</p></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search candidates..." className="w-64 rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-violet-500"/></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Name</th><th>Email</th><th>Role</th><th>Interviews</th><th>Avg Score</th><th>Status</th><th/></tr></thead><tbody>{candidates.map(c=><tr key={c.userId} className="border-t border-slate-100"><td className="px-5 py-4 font-semibold text-slate-900">{c.name}</td><td className="text-slate-500">{c.email}</td><td className="text-slate-600">{c.role}</td><td className="font-medium">{c.interviews}</td><td className="font-bold">{Math.round(c.averageScore)}%</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${c.status==='Active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{c.status}</span></td><td><ChevronRight size={17} className="text-slate-400"/></td></tr>)}</tbody></table></div></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-900">Recent Interviews</h2><div className="mt-4 space-y-3">{(data?.recentInterviews||[]).map(i=><div key={i.sessionId} className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><div><p className="font-semibold text-slate-800">{i.role}</p><p className="mt-1 text-xs text-slate-500">{i.difficulty} · {formatDate(i.startedAt)}</p></div><span className="font-bold text-violet-600">{Math.round(i.percentage)}%</span></div>)}</div></div><div className="rounded-2xl border border-violet-100 bg-gradient-to-br from-violet-50 to-white p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-600 text-white"><ShieldCheck size={19}/></span><div><h2 className="font-bold text-slate-900">Admin controls</h2><p className="text-sm text-slate-500">Manage your interview content.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><a href="/admin/questions" className="rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-700 hover:border-violet-200">Question Bank</a><a href="/admin/candidates" className="rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-700 hover:border-violet-200">Candidate List</a></div></div></section>
  </main></AppLayout>
}
function AdminStat({icon:Icon,label,value}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><Icon size={19}/></span><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-slate-900">{value??0}</p></div>}
function formatDate(v){return v?new Date(v).toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"}):"-"}
